name: iOS CI

on: [push, pull_request]

jobs:
  build-and-test:
    # Évite la migration surprise : fixe le runner (tu peux tester macos-15 plus tard)
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      # (Optionnel) Installe l’Xcode précis si besoin
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.4"

      # CocoaPods (si tu utilises Pods)
      - name: Install CocoaPods
        run: |
          gem install cocoapods --no-document
          cd ios
          pod install --repo-update
        if: ${{ hashFiles('ios/Podfile') != '' }}

      # Assure-toi que le schéma est *Shared* dans Xcode
      - name: Build
        run: |
          xcodebuild \
            -workspace ios/MonApp.xcworkspace \  # ou -project ios/MonApp.xcodeproj
            -scheme "MonApp" \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            -derivedDataPath build \
            clean build | xcpretty
        shell: bash

      - name: Test
        run: |
          xcodebuild \
            -workspace ios/MonApp.xcworkspace \
            -scheme "MonApp" \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            -derivedDataPath build \
            test | xcpretty
        shell: bash
